"""Write Ren'Py ``tl/<language>/`` translation files from translated units."""

from __future__ import annotations

import os
from collections import OrderedDict

from .extractor import DialogueUnit, ExtractResult, StringUnit, _game_dir
from .rpy_lex import quote_unicode, say_get_code

# Ren'Py language folder names keyed by our internal language code.
LANGUAGE_DIR = {
    "vietnamese": "vietnamese",
    "japanese": "japanese",
}


def _tl_root(game_root: str, language: str) -> str:
    return os.path.join(_game_dir(game_root), "tl", language)


def write_tl_files(game_root: str, language: str, result: ExtractResult) -> dict:
    """Generate tl files. Returns a small summary dict."""
    tl_root = _tl_root(game_root, language)

    # Remove previously generated translation scripts so a stale or broken file
    # from an earlier run cannot keep breaking the game. Non-script files
    # (fonts, images placed by the user) are left untouched.
    if os.path.isdir(tl_root):
        for dp, _dn, fns in os.walk(tl_root):
            for fn in fns:
                if fn.endswith((".rpy", ".rpyc")):
                    try:
                        os.remove(os.path.join(dp, fn))
                    except OSError:
                        pass

    by_file_dialogue: "OrderedDict[str, list[DialogueUnit]]" = OrderedDict()
    for d in result.dialogues:
        by_file_dialogue.setdefault(d.file_rel, []).append(d)

    by_file_strings: "OrderedDict[str, list[StringUnit]]" = OrderedDict()
    for s in result.strings:
        by_file_strings.setdefault(s.file_rel, []).append(s)

    all_files = list(dict.fromkeys(
        list(by_file_dialogue.keys()) + list(by_file_strings.keys())
    ))

    written = 0
    for rel in all_files:
        out_path = os.path.join(tl_root, rel)
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write("﻿")  # BOM, matching Ren'Py's own tl files
            f.write("# Generated by Ren'Py AI Translator.\n\n")

            for d in by_file_dialogue.get(rel, []):
                translated = d.translation or d.source_text
                trans_code = say_get_code(d.prefix, translated, d.suffix)
                f.write("# {}:{}\n".format(d.file_rel, d.line_no))
                f.write("translate {} {}:\n".format(
                    language, d.identifier.replace(".", "_")))
                f.write("\n")
                f.write("    # " + d.original_code + "\n")
                f.write("    " + trans_code + "\n")
                f.write("\n")

            strs = by_file_strings.get(rel, [])
            if strs:
                f.write("translate {} strings:\n".format(language))
                f.write("\n")
                for s in strs:
                    translated = s.translation or s.source_text
                    f.write("    # {}:{}\n".format(s.file_rel, s.line_no))
                    f.write('    old "{}"\n'.format(quote_unicode(s.source_text)))
                    f.write('    new "{}"\n'.format(quote_unicode(translated)))
                    f.write("\n")
        written += 1

    return {
        "files_written": written,
        "tl_root": tl_root,
        "dialogue_blocks": len(result.dialogues),
        "string_entries": len(result.strings),
    }
